@startuml
sprite $kafka [79x79/8] {
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaYXXXZaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaW001100GYaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaQ00Kaaa208aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaJ00YaaaG00aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaY00008000Gaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaP003KCCCK108Yaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaZG00Caaaaaaa300Paaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaY002SaaaaaaaaaC00GZaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaO003aaZOOZaZOOQaS200Yaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaZ801KaaaR00RY00Caaaa300Oaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaX002SaaaaR00G02SaaaaaaK108Zaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaZG00CaaaaaaR00308YaaaaaaaS200Xaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaY801SaaaaaaaR00RK00OaaaaaaaaB00Oaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaWO888003aaaaaaaaaR22SaS22AaaaaaaaaK108888OYaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaZ80144300PaaaaaaaaaaaaaaaaaaaaaaaaaaZ80144300Paaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaI00aaaaI0000000000000000000000000000000aaaaI00aaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaS10GXXW002SSSSSSSSSSSSSSSSSSSSSSSSSSK00GXXW00Aaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaS420013KaaaaaaaaaaaaaaaaaaaaaaaaaaaaS421013Caaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaZZYYZZaaaaaaaaaaaaaaaaaaZZYYZZaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaZWG00011000GXZaaaaaaaaaaZWG00011000OXZaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaYGOYaaaaaaYO001CSaaaaSC100OZaaaaaaYO002CSaaaaSC100OZaaaaaaYOGZaaaaaaaa
aaaaaaaaaS30008GG80003KaaaaaaaaaaK30008GG80013KaaaaaaaaaaK30008GG80013Saaaaaaaa
aaaaaaaaaaaaSKC44CKSaaaaaaaaaaaaaaaaSKC44CKSaaaaaaaaaaaaaaaaSKC44CKSaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaZWG880088GWZaaaaaaaaaaaaZWG880088GWZaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaXXaaaaaaaaYO0024CKKC4200GXaaaaaaaaXG0024CKKC4200GXaaaaaaaaXXaaaaaaaaaa
aaaaaaaaJ000GWWWWG0003SaaaaaaaaS3000GWWWWG0003SaaaaaaaaS3000GWWWWG000Jaaaaaaaaa
aaaaaaaaaaK43222234CaaaaaaZZaaaaaaK43222234KaaaaaaZZaaaaaaC43222234Kaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaYO80000008OXaaaaaaaaaaaaYO80000008OYaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaZOWZaaaaaaZX8004KSaaSK4108WZaaaaaaZW8004KSaaSK4008WZaaaaaaZWOZaaaaaaaaa
aaaaaaaaK3008GOOO8002CaaaaaaaaaaC2008OOOO8002CaaaaaaaaaaC2008OOOG8002Kaaaaaaaaa
aaaaaaaaaaaKC4334CKSaaaaaaaaaaaaaaaKC4334CKaaaaaaaaaaaaaaaSKC4334CKaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
}

!$COLOR = #aa62d2

!define kafka(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, $COLOR, kafka, kafka)
!define kafka(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, $COLOR, kafka, kafka)
!define kafka(e_alias, e_label, e_techn, e_descr, e_color) AzureEntity(e_alias, e_label, e_techn, e_descr, e_color, kafka, kafka)
@enduml