@startuml
sprite $ApiTransact [60x60/8] {
_________________--ssssssssssssssssssssss--_________________
______________-ssssssssssssssssssssssssssssss-______________
___________-ssssssssssssssssssssssssssssssssssss-___________
________--ssssssssssssssssssssssssssssssssssssssss--________
______-ssssssssssssssssssssssssssssssssssssssssssssss-______
____zsssssssssssssssssshWWWWWWWhsssssssssssssssssssssssz____
___-sssssssssssssssssssR0000000Rssssssssssssssssssssssss-___
__-ssssssssssssssssssssR0000000Rsssssssssssssssssssssssss-__
_-sssssssssssssssssrrrrR0000000Rrrrrrrrrssssssssssssssssss-_
_sssssssssssssssssi888800000000088888888Rjsssssssssssssssss_
ssssssssssssssssssa000000000000000000000Rjssssssssssssssssss
ssssssssssssssssssb222210000000122222222Skssssssssssssssssss
sssssssssssssssssssssssR0000000Rssssssssssssssssssssssssssss
sssssssssssssssssssssssR0000000Rssssssssssssssssssssssssssss
sssssssssssssssssssssssR0000000Rssssssssssssssssssssssssssss
sssssssssssssssssssssssR0000000Rssssssssssssssssssssssssssss
sssssssssssssssssssssssR0000000Rssssssssssssssssssssssssssss
sssssssssssssssssssssssR0000000Rssssssssssssssssssssssssssss
sssssssssssssssssssssssR0000000Rssssssssssssssssssssssssssss
tssssssssssssssssssssssR0000000Qssssssssssssssssssssssssssst
_ssssssssssssssssssssssS10000000Xpqrrrqqrssssssssssssssssss_
__ssssssssssssssssssssskJ000000000888809jsssssssssssssssss__
___ssssssssssssssssssssskK10000000000009jssssssssssssssss___
____rssssssssssssssssssssscL42100000123Cjssssssssssssssr____
_____tssssssssssssssssssssssskkkcccckkkssssssssssssssst_____
_______tsssssssssssssssssssssssssssssssssssssssssssst_______
__________tsssssssssssssssssssssssssssssssssssssst__________
____________ttsssssssssssssssssssssssssssssssstt____________
_______________ttsssssssssssssssssssssssssstt_______________
___________________tttssssssssssssssssttt___________________
}

!define ApiTransact(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, COLOR_DEFAULT_COMPONENTS, api, api)
!define ApiTransact(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, COLOR_DEFAULT_COMPONENTS, api, api)
!define ApiTransact(e_alias, e_label, e_techn, e_descr, e_color) AzureEntity(e_alias, e_label, e_techn, e_descr, e_color, api, api)
@enduml