@startuml
sprite $app_banking [70x70/8] {
0015LTaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaSRRRRRRRRRRRRRRRRRRRRRRRRJB2100
0DbjjjjbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaSSRRRRRRRRRRRRRRRRRRRRRRRRRJA0
JjjjjjjjjjbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaSRRRRRRRRRRRRRRRRRRRRRRRRRA
bjjjjjjjjjjbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaSSSSSSSSSSSSSSSSSSRRRRRRRR
jjjjjjjjssssssssssssssssssssssssssssssssssssssssssssssssssssssaRRRRRRR
jjjjjjjjsssssssssssrrrrrrqqqqqpppppppppppppppppppppppppppppsssaRRRRRRR
jjjjjjjjsssssssssssjjjjjjaaaaaRRRQJRQQQQRRRRRRRRRRRRRRRRRRRsssaRRRRRRR
jjjjjjjjsssssssssssjjjjjiaYXZaR000RQH009RROPQRRRRRRRRRRRRRRsssaRRRRRRR
jjjjjjjjsssssssssssjjjjja100GRR100IJ900IRH00ARRQRRRRRRRRRRRsssaRRRRRRR
jjjjjjjjsssssssssssjgO0Yaa300ORI00HR902RQ00AJIG08IRRRRRRRRRsssaRRRRRRR
jjjjjjjjssssssssssrU2000Oaa300RR009J80AQ00BRI002JRQPRRRRRRRsssbRRRRRRR
jjjjjjjjsssssssssnprjL2000XaB08S301R00RG0ARG02JIP800IRJRRRRsssbRRRRRRR
jjjjjjjjssssssssW000ehjT300WZ44JRRRRRRR2BI81BRG002BRJIQRRRRsssjRSRRRRR
jjjjjjjjssssssscE500008WhT4CSaaaRRRRRRRRJJBQG02BJQOG809RRRRsssjaaRRRRR
jjjjjjjjssssssposrscM6200JjaaaaaaSRRRRRRRRJJBQGG813AARRRRRRsssjaaaaSSR
jjjjjjjjssssss00008GemhibjjjaaaaaaSRRRRRRRRRR3BJIQPOG888IRRsssjaaaaaaR
jjjjjjjssssssk3211000000sjjjjaaaaaaSSRRRRRRRJR1122332AIRRRRsssjaaaaaaR
jkjjjjjssssssssssssstt-jkjjjjjbaaaaSOOOOOOOGGGGGGGGGGGGGIRRsssjaaaaaaa
jskjjjjssssssrO880000000sjjjjjjjbaaaaCCCCBBBBB0000000000IRRsssjaaaaaaa
jssskjjsssssss00001266UbrrsjjjjjjjbaaaaaaaaSR80000000000RRRsssjaaaaaaa
ksssssksssssssUMsksqom800WsskjjjjjjjbbaaaaaaS3100000000JSSSsssjaaaaaaa
sssssssssssssssqne0000015cpnrkkjjjjjjjjbaaW08XZS420000Aaaaasssjaaaaaaa
ssssssssssssssss500003MsqO001sookkkkjkhjP000000OYaaK43aaaaasssjaaaaaaa
sssssssssssssssssD16ksqW0001kr800Ss9000gj200000008Wajjbbbbjsssjaaaaaaa
ssssssssssssssssssssqW00003sr8000as90008jc200000002Tjjjjjjjsssjaaaaaaa
ssssssssssssssssssssU40004ssO0000ks90000Wsk200003Lkjjjjjjjjsssjaaaaaaa
sssssssssssssssssssssskEEssO00000ss900000hsk34Ekssssssssssssssjaaaaaaa
sssssssssssssssssssssssssskE6300Bss900002Essssssssssssssssssssjaaaaaaa
ssssssssssssssssssssssssssssssssssskkkssssssssssssssssssssssssjaaaaaaa
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssjabaaaaa
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssjjjjbaaa
rssssssssssssssssssssssssssrrrrrrrrrrrrrrjjjjjjjjjjjjjjjjjjjjjjjjjjjba
YsssssssssssssssssssssssssssskkjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjQ
0nssssssssssssssssssssssssssssssjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjiX0
008morssssssssssssssssssssssssssrrjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjige800
}

!define app_banking(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, COLOR_DEFAULT_COMPONENTS, app_banking, app_banking)
!define app_banking(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, COLOR_DEFAULT_COMPONENTS, app_banking, app_banking)
!define app_banking(e_alias, e_label, e_techn, e_descr, e_color) AzureEntity(e_alias, e_label, e_techn, e_descr, e_color, app_banking, app_banking)
@enduml