@startuml
sprite $core_transact [80x80/8] {
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssssrpnfnpqrssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssrpfH9999999BIgpsssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssroXLALkS99BBAEcsssogisssssssssssssssssssssssssssss
sssssssssssssssssssssssssssssjBJIYR9rP9IQsssssssW08sssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssqssULR999RfXissssR800hssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssbRssjRRA0UcsaIGGO20109ssssssssssssssssssssssssssss
sssssssssssssssssssssssssssssssSRiSSRR1mmsr800081418isssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssRRRjssR00pr10000gnH0Zsssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssbRRZsiR2008000000002Msssssssssssssssssssssssssss
sssssssssssssssssssssssssssssssskURRrRRI000000004Ecsssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssscbSRR900004Mkssssssssssssssssssssssssssssssss
sssssssssssssssssssssssssssssssssssssskUK14Essssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
ssssssrrrrrrrrrsrrrrrrrssrrssssssrrrssrrrrrrssrrsssssrrrsssssrrrssssssssrrssssss
sssssrH00000000kH00000AkR08gssssh80IsR000000kZ00Wssss808ssqWG800GOosspO800GQssss
ssssssUMM001MMcs900MMMcsR000Wsse000IsR00KMMUsR0008oss000sX005MMMD00Or909UMMkssss
sssssssss009ssss900eeehsR00208O0100IsR00OeefsR00500Wr000i00JsssssU00ZL008eosssss
sssssssss009ssss900666UsR00k3002U90IsR00466EsR00sc208000b00Qsssssp00SssE310Grsss
sssssssss009ssss900oooprR00ssMEss90IsR00XooorR00sss50000sC00eoqpe004sgmpqX00bsss
sssssssss10AssssA000009jR00ssssss90IsR000000jR00ssssU101ssc5100015Usk400003Mssss
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
ssssssssshshhrissrfsgrigrhijrigsiYsssisZisisgsoYshqrZshssrjsYirggshjqhsghrisssss
ssssssssskskkscsskkskkskskcsskkskkssskscksksksckskkscscsssckkcskkskskkskksksssss
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
}

!define core_transact(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, COLOR_DEFAULT_COMPONENTS, core_transact, core_transact)
!define core_transact(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, COLOR_DEFAULT_COMPONENTS, core_transact, core_transact)
!define core_transact(e_alias, e_label, e_techn, e_descr, e_color) AzureEntity(e_alias, e_label, e_techn, e_descr, e_color, core_transact, core_transact)
@enduml