@startuml
sprite $ibmmq_series [66x60/8] {
___________________________uuvwwxxxwwvuu__________________________
_____________________uw4DLSZgffeWXWXffgZSLDyw_____________________
__________________w4LigeNF______________7FVegaLyv_________________
_______________vyThWN7_______________________7NWiTyv______________
_____________vLiXN_______________________________NgbDv____________
___________vDiX____________________________________Ffjy___________
__________2bgF_______________________________________Fhcw_________
________uCiP_______9AAAA__________________uBAAA7______7XjB________
_______uKjG_________709I0_________________0R9___________HiC_______
_______JiN___________09I0_________________0J9____________PjB______
______1jP____________09I0333333333333333320R9_____________Yb9_____
_____uTa7____________09I0SgijrjjjjjjjjihYB0Q1_____________7iJ_____
_____9jQ_____________79I0jjbTZgjkjjifSTbja0R9______________Qb_____
_____Ij9______________9I0jrjjjbTSZSLjjjjja0R9______________Hj9____
_____Rj9______________9I0jjjjjjrjrkrjjjjrZ0R9______________9j9____
_____Qj9______________9I0OOWWOOWOOOOOOWWOG0R1______________9j9____
_____HjI______________8OHOOOOGOGOGOOGPOOOOOH8______________Ii0____
_____7jSu__________________________________________________SZ_____
______PjA_________________________________________________BjH_____
_______ZTu_________113122122__u3v_u44uu34vvCCCx__________vjY7_____
_______8hTu________I9R12BHIY20JQ9_0iiCAajJbO7FiJ________vbh7______
________FpTv_______I9R88GJI0PB9H9_1aHiaHjQiC2CbP_______wThF_______
_________7gbx______FFVNVVFF7FN_FF_7VFNV7WF7Vede8_____u4jYF________
___________OiLw_____________________________________wThN__________
____________FXiLw_________________________________xLhO7___________
______________7dhT4v___________________________w4bhV______________
_________________NWhTDxv___________________vyDbhdF________________
____________________FVXgaTD4yxxwwwwwxxy4DTagXVF___________________
_________________________7NdeefggggffeWdN7________________________
__________________________________________________________________
}

!define ibmmq_series(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, COLOR_DEFAULT_COMPONENTS, api, api)
!define ibmmq_series(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, COLOR_DEFAULT_COMPONENTS, api, api)
!define ibmmq_series(e_alias, e_label, e_techn, e_descr, e_color) AzureEntity(e_alias, e_label, e_techn, e_descr, e_color, api, api)
@enduml