@startuml
sprite $ibmmq_aix [78x64/8] {
___________________uvwwwwwwwwwwwww222222222222222222wwwu______________________
__________________uAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIv_____________________
_________________uAII82AAAAAAAAAAAAAAAAA222222222B3329HIIv____________________
________________vIIH0KaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaK1HIIw___________________
_______________vIIH1SaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaS2GII2__________________
______________1IIG2SaZaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaS2GIIA_________________
_____________9II82aaaaZaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa38IIA________________
____________AII8BaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaC8III_______________
___________AIH8BaaaaaZZYYYYaaaaaaaaaaaaaaaaaaaaaYYYYZaaaaZaK0HIIw_____________
_________uIII0JaaaaaaaSSSIIaaaaaaaaaaaaaaaaaaaaaAJSSSaaaaaaaS1HIIw____________
________vIIH1KaaaaaaaaaaaIIaaaaaaaaaaaaaaaaaaaaa9RaaaaaaaaaaaS1GIIw___________
_______1IIH1SaaaaaaaaaaaaIIaaaaaaaaaaaaaaaaaaaaaHRaaaaaaaaaaaaa2GIIA__________
______2IIG2aaaaaaaaaaaaaaIIaB00777777777777701Ba9Raaaaaaaaaaaaaa3GIIAv________
_____AII8BaaaaaaaaaaaaaaaIIa8GHww_________wAOF9a9RaaaaaaaaaaaaaaaC8IIAv_______
____AII8BaaaaaaaaaaaaaaaaIIa0___FVAxu_vx9VF___9a9RaaaaaaaaaaaaaaaaC8HIIv______
___IIH8KaaaaaaaaaaaaaaaaaJIa8_______NVN_______9a9RaaaaaaaaaaaaaaaaaK1HIIw_____
___HIA8ZaaaaaaaaaaaaaaaaaIIa0u_______________u9aHQaaaaaaaaaaaaaaaaaZGAIIF_____
____HIA8YaaaaaaaaaaaaaaaaIIaKKKKKKKKKKKKKKKKKKSaHRaaaaaaaaaaaaaaaaZ8AIIF______
_____GIA0YaaaaaaaaaaaaaaaJBIIIIIIIIIIIIIIIJIIIJJJJaaaaaaaaaaaaaaaZ0AIHF_______
______FII1PaaaSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaX1IIH7________
_______FII1OZaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaP1IIH7_________
________7II2GZaaaaaaaaaaaSaaaZaaaaaaaaaaaaaaaaaaaaZaaaZaaaaaaaO1II8___________
__________HI2GZaaaaaaZQZIKKJYZOaaaZGZaaPGPaZGGZYO9HOYaaaaaaaZG2II8____________
___________HIA8ZaaaaaRIRGWWWJRAHaaA9Saa910ZG10R0BaaB7ZaaaaaZ8AIIF_____________
____________NIA1YaaaaZIR9aaS9RIKPHS9SZa99380R0R1GZOG1aaaaaY8AIHF______________
_____________NIA1XaaaaKSCKKCSSKaKKaCSaaCCS4SS4SSC44CBaaaaY0AIH7_______________
______________FII1PaaaaaZaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaP1IIG_________________
_______________FII1OaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaO1IIG__________________
_________________HI2GZaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaZG2IIF___________________
__________________HI2GWWXWXXWWWWWWWWWWWWWWWWWWWWWWWWW8AIIF____________________
___________________GIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII7_____________________
_________________________FFFF7______________77777777__________________________
}

!define ibmmq_aix(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, COLOR_DEFAULT_COMPONENTS, ibmmq_aix, ibmmq_aix)
!define ibmmq_aix(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, COLOR_DEFAULT_COMPONENTS, ibmmq_aix, ibmmq_aix)
!define ibmmq_aix(e_alias, e_label, e_techn, e_descr, e_color) AzureEntity(e_alias, e_label, e_techn, e_descr, e_color, ibmmq_aix, ibmmq_aix)
@enduml