@startuml

!define BPD https://raw.githubusercontent.com/Projects-Kranio/bpd-architecture-plantuml-components/main/components

!includeurl BPD/Variables.puml

!$BOUNDARY_DESCR_MAX_CHAR_WIDTH ?= 35

!$TECHN_FONT_SIZE ?= 12
!$STEREOTYPE_FONT_SIZE ?= 12
!global $TRANSPARENT_STEREOTYPE_FONT_SIZE = $STEREOTYPE_FONT_SIZE/2

!$BOUNDARY_BG_COLOR ?= "transparent"
!$BOUNDARY_BORDER_STYLE ?= "dashed"
!$BOUNDARY_BORDER_COLOR ?= "#444444"

skinparam rectangle<<boundary>> {
    StereotypeFontSize $TRANSPARENT_STEREOTYPE_FONT_SIZE
    StereotypeFontColor $BOUNDARY_BG_COLOR
    BorderStyle $BOUNDARY_BORDER_STYLE
    BorderColor $BOUNDARY_BORDER_COLOR
}

!function $getLink($link)
  !if ($link != "")
    !return "[[" + $link + "]]"
  !else
    !return ""
  !endif
!endfunction

!unquoted function $breakText($text, $usedNewLine, $widthStr="-1")
!$width = %intval($widthStr)
!$multiLine = ""
!if (%strpos($text, "\n") >= 0)
  !while (%strpos($text, "\n") >= 0)
    !$brPos = %strpos($text, "\n")
    !if ($brPos > 0)
      !$multiLine = $multiLine + %substr($text, 0, $brPos) + $usedNewLine
    !else
      ' <U+00A0> non breaking change that newLine breaks with formats can be used with \n\n 
      !$multiLine = $multiLine + "<U+00A0>" + $usedNewLine
    !endif
    !$text = %substr($text, $brPos+2)
    !if (%strlen($text) == 0)
      !$text = "<U+00A0>"
    !endif
  !endwhile
!else
  !while ($width>0 && %strlen($text) > $width)
    !$brPos = $width
    !while ($brPos > 0 && %substr($text, $brPos, 1) != ' ')
      !$brPos = $brPos - 1
    !endwhile

    !if ($brPos < 1)
      !$brPos = %strpos($text, " ")
    !else
    !endif

    !if ($brPos > 0)
      !$multiLine = $multiLine + %substr($text, 0, $brPos) + $usedNewLine
      !$text = %substr($text, $brPos + 1)
    !else
      !$multiLine = $multiLine+ $text
      !$text = ""
    !endif
  !endwhile
!endif
!if (%strlen($text) > 0)
  !$multiLine = $multiLine + $text
!endif
!return $multiLine
!endfunction

!unquoted function $breakLabel($text)
!$usedNewLine = "\n== "
!$multiLine = $breakText($text, $usedNewLine)
!return $multiLine
!endfunction

!unquoted function $breakDescr($text, $widthStr)
  !$usedNewLine = "\n"
  !return $breakText($text, $usedNewLine, $widthStr)
!endfunction

' ------------------------------------------------------------------
' ------------------------------ CARD ------------------------------
' ------------------------------------------------------------------

!function $getBoundary($label, $sub_title, $descr)
  !$line = '== '
  !$line = $line + $breakLabel($label)
  !if ($sub_title != "")
    !$line = $line + '\n<size:' + $TECHN_FONT_SIZE + '>[' + $sub_title + ']</size>'
  !endif
  !if ($descr != "")
    !$line = $line + '\n\n' + $breakDescr($descr, $BOUNDARY_DESCR_MAX_CHAR_WIDTH)
  !endif
  !return $line
!endfunction

!unquoted procedure Boundary($alias, $label, $sub_title="", $descr="", $link="")
rectangle "$getBoundary($label, $sub_title, $descr)" <<boundary>> as $alias $getLink($link)
!endprocedure

' ------------------------------------------------------------------
' ------------------------------ LINE ------------------------------
' ------------------------------------------------------------------

' !global $propTable = ""

!$LINE_TYPE_SOLID = plain
!$LINE_TYPE_DASHED = dashed
!$LINE_TYPE_DOTTED = dotted

!$LINE_TIP_TYPE_ARROW = ">"
!$LINE_TIP_TYPE_BIG_ARROW = "|>"
!$LINE_TIP_TYPE_ASTERISK = "*"
!$LINE_TIP_TYPE_CIRCLE = "o"
!$LINE_TIP_TYPE_NONE = ""
!$LINE_TIP_TYPE_JUNK = "#"
!$LINE_TIP_TYPE_X = "x"
!$LINE_TIP_TYPE_KEYS = "}"
!$LINE_TIP_TYPE_PLUS = "+"

!$LINE_TIP_TYPE_ARROW_LEFT = "<"
!$LINE_TIP_TYPE_BIG_ARROW_LEFT = "<|"

!$LINE_SIZE_SMALL = 1
!$LINE_SIZE_MEDIUM = 2
!$LINE_SIZE_LARGE = 4
!$LINE_SIZE_DEFAULT = $LINE_SIZE_SMALL

!$LINE_DIRECTION_RIGHT = RIGHT
!$LINE_DIRECTION_LEFT = LEFT
!$LINE_DIRECTION_DOWN = DOWN
!$LINE_DIRECTION_UP = UP

' !$REL_TECHN_MAX_CHAR_WIDTH ?= 35
' !$REL_DESCR_MAX_CHAR_WIDTH ?= 32

!$COLOR_DEFAULT_LINE = COLOR_GRAY

' !$lastIndex = 0
' !$index = 1

' !function Index($offset=1)
'   !$lastIndex = $index
'   !$index = $lastIndex + $offset
'   !return $lastIndex
' !endfunction

' !unquoted function $getPrefix($index)
'   !if ($index == "")
'     !$pre = Index() + ": "
'   !else
'     !$pre = $index + ": "
'   !endif
'   !return $pre
' !endfunction

' !unquoted function $toRelArg($arg, $tags, $varPostfix)
'   !if ($arg > "")
'     !return $arg
'   !endif

'   !if (%strlen($tags) == 0)
'        !return $arg
'   !endif
'   !$brPos = %strpos($tags, "+")
'   !while ($brPos >= 0)
'     !$tag = %substr($tags, 0, $brPos)
'     !$newArg = %get_variable_value("$" + $tag + $varPostfix)
'     !if ($newArg > "")
'        !return $newArg
'     !endif
'     !$tags = %substr($tags, $brPos+1)
'     !$brPos = %strpos($tags, "+")
'   !endwhile
'   !if (%strlen($tags) > 0)
'     !$newArg = %get_variable_value("$" + $tags + $varPostfix)
'     !if ($newArg > "")
'        !return $newArg
'     !endif
'   !endif
'   !return $arg
' !endfunction

' !unquoted function $toStereos($tags)
'   !if (%strlen($tags) == 0)
'     !return ''
'   !endif
'   !$stereos = ''
'   !$brPos = %strpos($tags, "+")
'   !while ($brPos >= 0)
'     !$tag = %substr($tags, 0, $brPos)
'     !$stereos = $stereos + '<<' + $tag + '>>'
' %set_variable_value("$" + $tag + "_LineLegend", %true())
'     !$tags = %substr($tags, $brPos+1)
'     !$brPos = %strpos($tags, "+")
'   !endwhile
'   !if (%strlen($tags) > 0)
'     !$stereos = $stereos + '<<' + $tags + '>>'
' %set_variable_value("$" + $tags + "_LineLegend", %true())
'   !endif
'   !return $stereos
' !endfunction

' !unquoted function $breakTechn($text, $widthStr)
'   !$usedNewLine = '</size>//\n//<size:'+$TECHN_FONT_SIZE+'>'
'   !return $breakText($text, $usedNewLine, $widthStr)
' !endfunction

' format sprite that it can be used in diagram
' !function $getSprite($sprite)
'   !if (%substr($sprite, 0, 1) != "&" && %substr($sprite, 0, 4) != "img:")
'     !$formatted = "<$" + $sprite + ">"
'   !else
'     !$formatted = "<" + $sprite + ">"
'   !endif
'   !return $formatted
' !endfunction

' !unquoted function $getProps($alignedNL = "\n")
'   !if ($propTable != "")
'     !$retTable = $alignedNL + $propTable
'     !$propTable = ""
'     !return $retTable
'   !endif
'   !return ""
' !endfunction

!function $getRel($direction, $alias1, $alias2, $label, $techn, $descr, $sprite, $tags, $link)
  ' !$sprite = $toRelArg($sprite, $tags, "RelTagSprite")
  ' !$techn = $toRelArg($techn, $tags, "RelTagTechn")
  !$rel = $alias1 + ' ' + $direction + ' ' + $alias2
  ' !if ($tags != "")
  '   !$rel = $rel + ' ' + $toStereos($tags)
  ' !endif
  ' !$rel = $rel + ' : '
  ' !if ($link != "")
  '   !$rel = $rel + '**[[' + $link + ' '
  ' !endif
  ' !if ($sprite != "")
  '   !$rel = $rel + $getSprite($sprite)
  '   !if ($label != "")
  '     !$rel = $rel + ' '
  '   !endif
  ' !endif
  ' !if ($link != "")
  '   !$usedNewLine = ']]**\n**[[' + $link + ' '
  '   ' if sprite and label is empty than the link url is shown (otherwise link cannot be activated at all)
  '   !$rel = $rel + $breakText($label, $usedNewLine) + ']]**'
  ' !else
  '   !if ($label != "")
  '     !$usedNewLine = '**\n**'
  '     !$rel = $rel + '**' + $breakText($label, $usedNewLine) + '**'
  '   !else
  '     !$rel = $rel + '<size:0>.</size>'
  '   !endif
  ' !endif
  ' !if ($techn != "")
  '   ' line break is not deterministic, calculate it
  '   !$rel = $rel + '\n//<size:' + $TECHN_FONT_SIZE + '>[' + $breakTechn($techn, $REL_TECHN_MAX_CHAR_WIDTH) + ']</size>//'
  ' !endif
  ' !if ($descr != "")
  '   ' line break is not deterministic, calculate it
  '   !$rel = $rel + '\n\n' + $breakDescr($descr, $REL_DESCR_MAX_CHAR_WIDTH)
  ' !endif
  ' !$prop = $getProps()
  ' !if ($prop != "")
  '   ' reuse table
  '   !$rel = $rel + $prop
  ' !endif
  !return $rel
!endfunction

' !unquoted function $getDirection($index, $tipLineFrom, $tipLineTo, $bidirectional=false, $typeLine=$LINE_TYPE_SOLID, $color=$COLOR_DEFAULT_LINE, $size=$LINE_SIZE_DEFAULT, $direction=$LINE_DIRECTION_RIGHT)
'   !if ($index == "")
'     !$pre = Index() + ": "
'   !else
'     !$pre = $index + ": "
'   !endif
'   !return $pre
' !endfunction

!unquoted procedure Line($from, $to, $label, $techn="", $descr="", $sprite="", $tags="", $link="")
'!$pre = $getPrefix($index)
'$pre + $label
$getRel("-->>", $from, $to, $label, $techn, $descr, $sprite, $tags, $link)
!endprocedure

!unquoted procedure Rel_D($from, $to, $label, $techn="", $descr="", $sprite="", $tags="", $link="")
$getRel("-->>", $from, $to, $label, $techn, $descr, $sprite, $tags, $link)
!endprocedure

@enduml