@startuml diagram_test

!define BPD https://raw.githubusercontent.com/Projects-Kranio/bpd-architecture-plantuml-components/main/components

!includeurl BPD/plantuml/common/foo.puml
!includeurl BPD/plantuml/common/api.puml
!includeurl BPD/plantuml/banking/ApiTransact.puml
!includeurl BPD/AzureCommon.puml
!includeurl BPD/Transversal.puml

!includeurl BPD/C4Model.puml

Boundary(lvl1, "Openshift Interno", "10.0.0.3") {
  Boundary(tr, "Transversal") {
    Transversal()
  }

  ApiTransact(idtrans, "HTTPS 8080", "API Transact")

  Boundary(lvl2, "") {
    Boundary(card2, "") {
      api(id3, "label", "name")
    }

    Boundary(userCard, "Test", "test2") {
      foo(id, "", "test", "", "#0072C6")
    }

    Boundary(card, "") {
      foo(id2, "test", "test","desc")
    }
  }
}

Line(id_tr_1, id3, "")

@enduml