@startuml
' plantuml-multi-cloud-diagrams
' https://github.com/gamma-data/plantuml-multi-cloud-diagrams

!define BPD https://raw.githubusercontent.com/Projects-Kranio/bpd-architecture-plantuml-components/main/components
!define C4Puml https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master

!includeurl BPD/plantuml/common/foo.puml
!includeurl BPD/plantuml/common/api.puml
!includeurl BPD/AzureCommon.puml
!includeurl BPD/Transversal.puml
!includeurl C4Puml/C4_Context.puml
!includeurl C4Puml/C4_Component.puml
!includeurl C4Puml/C4_Container.puml

'left to right direction

title Example  Components

Boundary(lvl1, "") {
  Boundary(tr, "Transversal") {
    Transversal()
  }

  Boundary(lvl2, "") {
    Boundary(card2, "") {
      api(id3, "test", "test")
    }

    Boundary(userCard, "") {
      foo(id, "test", "test", "", "#0072C6")
    }

    Boundary(card, "") {
      foo(id2, "test", "test", "desc")
    }
  }
}


Rel_R(id, id2, "")
Rel_R(id3, tr, "")

@enduml