@startuml

!definelong Transversal()
    !define BPD https://raw.githubusercontent.com/Projects-Kranio/bpd-architecture-plantuml-components/main/components
    !define C4Puml https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master

    !includeurl BPD/general/foo.puml
    !includeurl BPD/general/api.puml
    !includeurl BPD/AzureCommon.puml
    !includeurl C4Puml/C4_Context.puml
    !includeurl C4Puml/C4_Component.puml
    !includeurl C4Puml/C4_Container.puml

    Boundary(tr_1, "") {
        foo(id_tr_1, "API 1", "ms-api-1", "", "#6ae515")
    }

    Boundary(tr_2, "") {
        foo(id_tr_2, "API 2", "ms-api-2", "", "#6ae515")
    }

    Rel_R(id_tr_2, id_tr_1, "")
!enddefinelong

@enduml